""""add-car-model-columns"

Revision ID: 34a1de6f3e07
Revises: 9df3ac4f1e39
Create Date: 2022-03-09 09:47:29.439069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a1de6f3e07'
down_revision = '9df3ac4f1e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('img_url', sa.String(length=128), nullable=True))
    op.add_column('model', sa.Column('person_capacity', sa.Integer(), nullable=True))
    op.add_column('model', sa.Column('trunk_capacity', sa.Integer(), nullable=True))
    op.add_column('model', sa.Column('avg_fuel_consumption', sa.Float(), nullable=True))
    op.add_column('model', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('model', sa.Column('width', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'width')
    op.drop_column('model', 'height')
    op.drop_column('model', 'avg_fuel_consumption')
    op.drop_column('model', 'trunk_capacity')
    op.drop_column('model', 'person_capacity')
    op.drop_column('model', 'img_url')
    # ### end Alembic commands ###
