""""remove-img-column"

Revision ID: 35b0dc9c4349
Revises: 510d78013e1b
Create Date: 2022-03-09 11:36:08.981080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b0dc9c4349'
down_revision = '510d78013e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('img_url', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
