""""change-length-type"

Revision ID: 3f6e3d7ffd91
Revises: 640ae0178b8d
Create Date: 2022-03-09 11:09:35.257823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6e3d7ffd91'
down_revision = '640ae0178b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
