"""add length column with fixed type

Revision ID: 510d78013e1b
Revises: c1f5d50a01d6
Create Date: 2022-03-09 11:16:59.500441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510d78013e1b'
down_revision = 'c1f5d50a01d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('length', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'length')
    # ### end Alembic commands ###
