"""remove length column

Revision ID: c1f5d50a01d6
Revises: 3f6e3d7ffd91
Create Date: 2022-03-09 11:14:56.607322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f5d50a01d6'
down_revision = '3f6e3d7ffd91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
