""""add-img-with-longer-char-limit"

Revision ID: c606729ce427
Revises: 35b0dc9c4349
Create Date: 2022-03-09 11:36:43.939094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c606729ce427'
down_revision = '35b0dc9c4349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('img_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'img_url')
    # ### end Alembic commands ###
