version: '3.3'
services:
  db:
    container_name: 'db'
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=fastapi
      - POSTGRES_DB=car_rental
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
  api:
    build:
      context: ./fastapi-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

volumes:
  postgres:
