version: '3.3'

services:
  db:
    env_file:
      - ./env/db.env
    container_name: 'db'
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  db_admin:
    container_name: 'db_admin'
    image: dpage/pgadmin4
    env_file:
     - ./env/db_admin.env
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
  api:
    depends_on:
      - 'db'
    env_file:
      - ./env/api.env
    container_name: 'api'
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/src

volumes:
  postgres:
  pgadmin:
